---
title: "seabirds_project"
author: "Stephanie Duncan"
date: "14/12/2020"
output: html_document
---

```{r}
library(tidyverse)
library(janitor)
library(here)
library(readr)
library(readxl)
library(dplyr)
library(tidyr)
library(assertr)

#Testing where the top level of the project directory is
here::here()

#Setting the path to the data file
seabirds <- read_csv(here("clean_data/seabirds_data.csv"))
```

1. Which bird had the most individual sightings?
```{r}
most_individual_sightings <- seabirds %>% 
  filter(count == 1) %>% 
  group_by(bird_common_name, bird_scientific_name, species_abbreviation) %>% 
  summarise(bird_sightings_total = n()) %>% 
  arrange(desc(bird_sightings_total)) %>% 
  head(1)
```

2. Which bird had the highest total count?

```{r}
bird_highest_total_count <- seabirds %>% 
  group_by(bird_common_name, bird_scientific_name, species_abbreviation) %>% 
  summarise(total_count = sum(count)) %>% 
 arrange(desc(total_count)) %>% 
   head(1) 
  
#Species PUFTEN has the highest total count
```


3. Which bird had the highest total count above a latitude of -30?

```{r}
highest_total_count_lat_30 <- seabirds %>% 
  filter(lat > -30) %>% 
  group_by(bird_common_name, bird_scientific_name, species_abbreviation) %>% 
  summarise(total_bird_count = sum(count)) %>% 
  arrange(desc(total_bird_count)) %>% 
  head(1)
```


4. How many different types of birds were only ever seen in groups of 1?

```{r}
groups_of_one <- seabirds %>% 
   mutate(groups_of_one_sightings = count) %>% 
    filter(groups_of_one_sightings == 1) %>% 
  group_by(bird_common_name, bird_scientific_name, species_abbreviation) %>% 
  summarise(groups_of_one_sightings = n()) 
```


5. How many penguins were seen? 
```{r}
penguins_seen <- seabirds %>% 
  filter(str_detect(bird_common_name, "[Pp]enguin")) %>% 
  #Checking the number of each type of penguin
  #group_by(bird_common_name, bird_scientific_name, species_abbreviation) %>% 
  summarise(number_of_penguins = sum(count)) 
#%>% arrange(desc(number_of_penguins))
```

Additional Analysis
6. Show the number of bird sightings by dates.
```{r}
birds_sightings_dates <- 
seabirds %>%
  filter(str_detect(date, "[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]")) %>% 
  group_by(date) %>% 
  summarise(number_of_bird_sightings = sum(count))
#There are quite a few gaps where sightings are not displayed for a few days or months, possibly due to bird sightings not being recorded or bird migration.
```




